import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppTopBar from "./components/layout/AppTopBar";
import LeftSideBar from "./components/layout/LeftSideBar";
import AppHeader from "./components/layout/AppHeader";
import AppFooter from "./components/layout/AppFooter";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "PWA-OCS-CLONE",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}>
                <AppTopBar />
                <div className="flex">
                    <LeftSideBar />
                    <div className="w-full h-[calc(100dvh-3rem)] overflow-y-auto">
                        <AppHeader />
                        <main className="w-full bg-gray-100 p-4 min-h-[calc(100dvh-9rem)]">
                            <div className="border h-full w-full rounded-md p-3 border-gray-300">{children}</div>
                        </main>
                        <AppFooter />
                    </div>
                </div>
            </body>
        </html>
    );
}
